# Very Good Analysis (https://pub.dev/packages/very_good_analysis)
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**/**.codegen.g.dart'

linter:
  rules:
    always_put_required_named_parameters_first: false
    one_member_abstracts: false
