targets:
  $default:
    builders:
      json_serializable|json_serializable:
        options:
          explicit_to_json: true
          checked: true
      freezed:freezed:
        generate_for:
          include:
            - lib/**.codegen.dart
      riverpod_generator:
        generate_for:
          include:
            - lib/**.codegen.dart