name: ez_fit_app
description: Fitness app for coaches and athletes
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: '>=3.0.2 <3.17.0'
  flutter: 3.16.9

dependencies:
  cached_network_image: ^3.4.1
  country_flags: ^3.0.0
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7
  email_validator: ^3.0.0
  faker: ^2.2.0
  file_picker: ^8.1.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.14
  freezed_annotation: ^2.4.4
  go_router: ^14.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: any
  json_annotation: ^4.9.0
  phone_numbers_parser: ^9.0.1
  quick_log: ^5.5.0
  responsive_grid_list: ^1.4.0
  riverpod_annotation: ^2.6.1
  rxdart: ^0.28.0
  share_plus: ^10.1.2
  skeletonizer: ^1.4.2
  supabase_flutter: ^2.8.0
  super_drag_and_drop: ^0.8.24
  syncfusion_flutter_datagrid: ^27.1.58
  toastification: ^2.3.0
  vector_math: ^2.1.4
  web_smooth_scroll: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/dummy/
    - assets/images/characters/
    - assets/flag_icons/
    - .env
  fonts:
    - family: Prototype
      fonts:
        - asset: assets/fonts/Prototype.ttf
    - family: HeroIcons
      fonts:
        - asset: assets/fonts/HeroIconSolid.ttf