name: impostor
description: Impostor game.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: '>=3.0.2 <3.17.0'
  flutter: 3.16.9

dependencies:
  collection: ^1.16.0
  country_flags: ^3.0.0
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  go_router: ^14.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: any
  json_annotation: ^4.8.1
  quick_log: ^5.3.1
  responsive_grid_list: ^1.4.0
  riverpod_annotation: ^2.3.3
  rxdart: ^0.28.0
  share_plus: ^10.0.2
  short_uuids: ^2.0.0
  vector_math: ^2.1.4
  web_smooth_scroll: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.6.7
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/avatar/
    - assets/images/medals/
    - assets/hero_icons/
    - assets/flag_icons/
  fonts:
    - family: Prototype
      fonts:
        - asset: assets/fonts/Prototype.ttf
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
